FreeRTOS/iot-reference-arm-corstone3xx

Projects/blinky/CMakeLists.txt

blinky: Fix compilation failure
Description
-----------
Add missing `app-config` interface library dependency to `freertos_config` interface library.
Test Steps
-----------
Verified changes on Corstone-300 platform.
Checklist:
----------
Related Issue
-----------

blinky: Fix compilation failure

---

Middleware/AWS/cmake/GenerateAWSUpdateDigestAndSignature.cmake
Projects/aws-iot-example/CMakeLists.txt

Description
-----------
A new CMake module (GenerateAWSUpdateDigestAndSignature.cmake) is introduced to be used to generate AWS update digest and update signature to be used for AWS OTA update.
This change would enhance code re-usability and decrease code duplication within the applications by using the newly introduced CMake module rather than duplicating the same code every time AWS Update digest and signature are to be generated. 
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add new CMake module to generate AWS update digest and signature

---

.github/.cSpellWords.txt
.github/workflows/build.yaml
.gitlab-ci.yml
Bsp/CMakeLists.txt
Docs/development-environment.md
Middleware/ARM/TF-M/cmake/MergeTfmImages.cmake
Middleware/ARM/TF-M/cmake/SignTfmImage.cmake
Projects/aws-iot-example/CMakeLists.txt
Projects/aws-iot-example/provisioning/CMakeLists.txt
Projects/blinky/CMakeLists.txt
Tools/cmake/ConvertElfToBin.cmake
Tools/scripts/run.sh
conftest.py

Description
-----------
* SignTfmImage.cmake is introduced to add the needed sign function to be used to sign the non-secure (application) binaries.
* MergeTfmImages.cmake is introduced to be used to merge Bootloader, TF-M secure, Non-secure user application, secure and non-secure provisioning images into one image to be loaded inside the ROM rather than loading different images at their respective addresses.
* These change enhance re-usability and decrease code duplication within the existing applications and applications to be added.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add signing merging cmake modules

---

.github/workflows/build.yaml
.github/workflows/ci.yml
.github/workflows/formatting.yml
Bsp/common/bsp_serial.c
Bsp/common/bsp_serial.h
Config/freertos-config/FreeRTOSConfig.h
Docs/aws-iot-example.md
Middleware/ARM/IoT_VSocket-lib/transport_tls_iot_socket.c
Middleware/ARM/freertos-ota-pal-psa-lib/src/ota_provision.c
Middleware/ARM/freertos-ota-pal-psa-lib/src/ota_provision.h
Middleware/ARM/mbedtls-lib/src/tls_helper.h
Projects/aws-iot-example/dev_mode_key_provisioning.c
Projects/aws-iot-example/mqtt-agent-wrapper/mqtt_agent_task.c
manifest.yml

Description
-----------
Use ubuntu 20.04 for formatting so that this repo can use the same formatting as all other FreeRTOS Repos
CMSIS Is not directly included in this repo, removing it from this repo's manifest.yml file
Fix a broken link in the aws-iot-example.md file, remove the trailing comma from a link, and add an exclude for a bash link
Add the link and manifest verification workflow to this repo. Bump checkout actions to v3 to remove the deprecation warnings
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Link and Manfiest Verification CI-CD Checks, use FreeRTOS/CI-CD Formatting Action

---

Tools/scripts/run_uncrustify.sh
Tools/uncrustify.cfg
release_changes/202311150923.change

Description
-----------
The --check option was used to check for uncrustify failures, it is better to use --replace instead of --check as it corrects the failures beside doing what --check does. Developers can benefit from this improvement when they run the pre-commit locally.
Uncrustify should check for all the FRI project files except for those that are downloaded with git submodule, to do so, we have to de-init all the submodules before Uncrustify tool run and then initialise them back right after it finish.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Uncrustify: use replace option

---

bsp/CMakeLists.txt
bsp/common/bsp_serial.c
release_changes/202401041514.change

Description
-----------
The serial driver is used by multiple tasks and not all tasks use the Log APIs to send data to the serial driver.
This was causing serial data buffer corruption.
Synchronise the access of the serial driver using mutual exclusion to make it thread-safe.
This also removes code duplication and fixes return values for
the write system call:
* Arm GNU Toolchain: On failure, `-1`.
On success, total chars written.
* Arm Compiler: On failure, a positive number representing the number of
chars NOT written or a negative number indicating an error.
On success, `0`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

bsp: synchronize serial access

---

release_changes/202401091359.change
tools/scripts/build.sh
tools/scripts/run.sh

Description
-----------
The additional optional argument is useful to allow the end user to create multiple build directories
for various applications and/or variants.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

build: Add optional argument for build directory path specification

---

release_changes/202401111515.change
tools/scripts/build.sh

Description
-----------
Allow Blinky app to be built without setting certificates
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

build: Do not require certificate and key for Blinky

---

.gitlab-ci.yml
applications/keyword_detection/CMakeLists.txt
applications/keyword_detection/configs/app_config/app_config.h
applications/keyword_detection/main.c
applications/keyword_detection/ml_interface.cc
applications/speech_recognition/CMakeLists.txt
applications/speech_recognition/configs/app_config/app_config.h
applications/speech_recognition/dsp/src/dsp_task.cc
applications/speech_recognition/main.c
bsp/CMakeLists.txt
bsp/patches/0001-corstone300-Add-missing-FVP-VSI-handlers.patch
bsp/patches/0002-platform-irq-Add-VSI-IRQ-numbers-for-CS300-and-CS310.patch
bsp/patches/0003-bsp-Add-CMSIS-Driver-implementation-for-VSI.patch
docs/keyword_detection.md
docs/prerequisites.md
docs/speech_recognition.md
release_changes/202401051109.change
tools/scripts/arm_vsi0.py
tools/scripts/build.sh
tools/scripts/run.sh
tools/scripts/setup_python_vsi.sh
tools/tests/conftest.py
tools/tests/test_ota.py

Description
-----------
Add support for VSI as the input audio source for the existing ML applications.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add support for VSI as an input audio source

---

components/ai/ml_embedded_evaluation_kit/CMakeLists.txt
components/aws_iot/corepkcs11/CMakeLists.txt
components/aws_iot/ota_for_aws_iot_embedded_sdk/CMakeLists.txt
components/connectivity/iot_vsocket/CMakeLists.txt
components/security/trusted_firmware-m/CMakeLists.txt
docs/project_organisation.md
release_changes/202401301136.change
tools/cmake/ApplyPatches.cmake

This new way of applying patches is added to fix Corstone300 platform hardfault exception happening as the TF-M patch
(components/security/trusted_firmware-m/integration/patches /0001-corstone300-Modify-ISRAM0-to-be-non-secure-partition.patch) for this platform is sometimes not applied.
Patches are now applied using `git stash` and
`git apply`. This methodology is much better as
it reports whenever the new CMake function fails
to apply a certain patch.
Note:
This solution is based on what TF-M implemented in `components/security/trusted_firmware-m/library/cmake/ remote_library.cmake`
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …

patches: Use robust patches function to fix corstone300's hardfault

---

.gitlab-ci.yml
applications/aws_iot_example/freertos_integration_tests/integration_tests_platform_function.c
applications/aws_iot_example/freertos_integration_tests/test_param_config.h
components/connectivity/freertos_plus_tcp/integration/src/transport_mbedtls.c
components/security/freertos_ota_pal_psa/CMakeLists.txt
components/security/freertos_ota_pal_psa/integration/patches/0001-ota-abort-Fix-successful-abortion-check.patch
components/tools/freertos_libraries_integration_tests/CMakeLists.txt
components/tools/freertos_libraries_integration_tests/integration/patches/0001-Reduce-the-TRANSPORT_TEST_BUFFER_WRITABLE_LENGTH.patch
release_changes/202401191456.change
tools/tests/conftest.py
tools/tests/test_integration.py

Description
-----------
Fix nightly build failure
Test Steps
-----------
The changes validated in the CI as well as in nightly jobs. No regression found.
Checklist:
----------
Related Issue
-----------

Fix nightly build failure

---

applications/freertos_iot_libraries_tests/CMakeLists.txt
applications/freertos_iot_libraries_tests/test_param_config.h
release_changes/202402131559.change

Description
-----------
Change the optimization level for the `freertos-iot-libraries-tests` application to reduce code size whilst still maintaining a comfortable debugging experience.
Arm Compiler For Embedded optimization level is set to use `-O1` and Arm GNU Toolchain is set to use `-Og`.
These optimization levels are already used by the other FRI applications.
The Arm Compiler For Embedded `-O1` optimization level results in a slower binary execution speed on `FVP_Corstone_SSE-310`. The MQTT test process loop timeout period
(`MQTT_TEST_PROCESS_LOOP_TIMEOUT_MS`) needs therefore to be increased from `40000` to `54630` to pass the
`MqttTest, MQTT_Restore_Session_Duplicate_Incoming_Publish_Qos1` test case.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By …

integration-app: Reduce binary code size with debug experience

---

CMakeLists.txt

build: Fix missing executable suffix
Description
-----------
Add missing PARENT_SCOPE to root folder CMakeLists.txt. It is needed as the entry point is the application/<example>.
Test Steps
-----------
All platforms are tested with all the examples. The resulting application files are manually verified to have to correct suffix.
Checklist:
----------
Related Issue
-----------

build: Fix missing executable suffix

---

applications/freertos_iot_libraries_tests/CMakeLists.txt
release_changes/202403151803.change

Description
-----------
The `freertos-iot-libraries-tests` application
was mistakenly relying on another app's TF-M configuration file. The other app (`aws-iot-example`) was removed along with its configuration files.
The `freertos-iot-libraries-tests` application now uses its own TF-M configuration file.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

lib-tests-app: Fix build issue

---

components/ai/ml_embedded_evaluation_kit/CMakeLists.txt
components/ai/ml_embedded_evaluation_kit/integration/cmake/ConvertAudioSourceToCode.cmake
components/ai/ml_embedded_evaluation_kit/integration/cmake/SetupMlEmbeddedEvaluationKitLibraries.cmake
components/ai/ml_embedded_evaluation_kit/integration/patches/0001-use-case-resources-User-selectable-model-resources.patch
release_changes/202403121559.change

Description
-----------
When building ML apps, the MLEK downloads model resources for the model specified by a given application.
The FRI integration of the MLEK prevents these resources from being re-donwloaded if they already exist to speed up build time.
However, in the case of a different application being build, model resources have to be re-downloaded as different ML applications use different models.
To allow the re-download of model resources, the generated ML model resources subdirectory is now generated in the CMake build directory.
Building a different application requires triggering a clean build which will also delete the resources specific to a model used by another application.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By submitting this pull …

ml-apps: Fix building different ML apps subsequently

---

.gitlab-ci.yml
pyproject.toml
release_changes/202404051247.change

Description
-----------
Pipeline matrices are divided based on the targets to decrease the number of build jobs needed for `test-applications` job as they would exceed the limit (50 jobs) after adding support for software inference with speech-recognition application for all platforms, the limitation of 50 jobs comes from `needs` keyword used in `test-applications` job.
This PR also include the following changes for internal CI:
* Move testing ML applications built with GNU toolchain to nightly build scheduled pipeline.
* Move testing applications with software inference to nightly build scheduled  pipeline.
* Move testing applications with VSI as input audio source to nightly build scheduled pipeline.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By submitting …

Optimise Internal CI

---

.github/.cSpellWords.txt
release_changes/202404251016.change
tools/ci/pipeline-baseline-fri.yml

Description
-----------
`cspell` is used as the spell checker tool to follow Public GitHub repository spell check process.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add spell-checker to internal CI

---

README.md
applications/freertos_iot_libraries_tests/CMakeLists.txt
applications/keyword_detection/CMakeLists.txt
applications/object_detection/CMakeLists.txt
applications/speech_recognition/CMakeLists.txt
components/security/mbedtls/integration/CMakeLists.txt
docs/components/security/mbedtls/mbedtls.md
docs/components/security/trusted_firmware-m/trusted_firmware-m.md
release_changes/202403221755.change

Description
-----------
Add/enhance documentations for the following components:
- Trusted-firmware-m
- Mbed TLS
- Top level README.md
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add documentation enhancements

---

.gitlab-ci.yml
release_changes/202404301414.change

Description
-----------
With https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/commit/4471af64de1d481374881917bbba8736b1217530, a validation logic has been introduced which checks, if one of the address in an IP packet is loopback then both source and destination addresses must be loopback. For network interface tests, we run the server on the local machine and use loopback interface address in integration tests to communicate with the server. This causes validation logic to fail, as the destination address in the IP in the packet returned by the server is not a loopback address, but instead address assigned to the device. As a workaround, we use the ethernet interface address of the host machine instead of loopback to communicate with the server.
In addition, add a job retry logic to nightly …

integration-tests: Fix nightly job failures

---

applications/blinky/configs/freertos_config/CMakeLists.txt
applications/freertos_iot_libraries_tests/configs/freertos_config/CMakeLists.txt
applications/keyword_detection/configs/freertos_config/CMakeLists.txt
applications/object_detection/configs/freertos_config/CMakeLists.txt
applications/speech_recognition/configs/freertos_config/CMakeLists.txt
bsp/isp_mali-c55/integration/CMakeLists.txt
components/connectivity/freertos_plus_tcp/integration/CMakeLists.txt
components/freertos_kernel/CMakeLists.txt
manifest.yml
release_changes/202404301532.change

Description
-----------
Even though CMake supports circular dependency, but currently it is supported only for static libraries. If CMake detects a circular dependency which involves an object library then CMake stops. For more info, check https://gitlab.kitware.com/cmake/cmake/-/issues/17905.
With FreeRTOS-Kernel 11.1.0 release, FreeRTOS-Kernel produces a single static library. As part of this effort, `freertos_kernel_port` library has been changed to an `OBJECT` library. With our current dependency chain in FRI, this leads to a circular dependency with an object library. Therefore, remove the dependency of `freertos_config` on `fri-bsp` to avoid this. Because of this, we've to add the necessary includes from bsp to `freertos-config`.
The CS315 network interface layer inside the FreeRTOS …

freertos-kernel: Update to `V11.1.0` release

---

.github/workflows/build.yaml
.gitlab-ci.yml
applications/freertos_iot_libraries_tests/CMakeLists.txt
components/tools/freertos_libraries_integration_tests/CMakeLists.txt
components/tools/freertos_libraries_integration_tests/integration/patches/0003-Increase-keep-alive-interval.patch
components/tools/freertos_libraries_integration_tests/integration/patches/0004-Enable-access-to-mbedtls-private-fields.patch
release_changes/202405211228.change

Description
-----------
The MQTT server resets connection if the device doesn't send keep alive packets within keep-alive interval, which is configured to 5 seconds by default. Increase the keep-alive interval to 60 seconds to avoid connection reset request when the device is busy.
Test Steps
-----------
Validated the changes in the nightly, no regressions observed.
Checklist:
----------
Related Issue
-----------

Increase mqtt keep alive

---

.gitlab-ci.yml
applications/speech_recognition/dsp/src/scheduler.cpp
bsp/corstone300/include/FreeRTOSConfig_target.h
bsp/corstone310/include/FreeRTOSConfig_target.h
bsp/corstone315/include/FreeRTOSConfig_target.h
release_changes/202405161554.change
tools/tests/test_applications.py
tools/tests/test_blinky_output.py

Description
-----------
Changes done as part of this PR:
* The block time for the DSP task in speech-recognition application is increased from `120` ms to `140` ms as it seems to be overusing the CPU which result in incorrect inference with Software inference engine configuration.
* pytests inside the nightly jobs `sw-vsi-config-test`, and `gnu-toolchain-test` should be run as part of the `script` section of these jobs as running the tests in the `after_script` section of these jobs won't have an influence on the exit code of the pipeline which might lead to false negative misleading CI results.
* Tick rates are modified for all platforms to fix `speech-recognition` application with software inference issues related to incorrect inferred sentence.
Test Steps
-----------
Checklist: …

Fix speech recognition application

---

components/connectivity/freertos_plus_tcp/integration/src/network_startup.c
manifest.yml
release_changes/202406141224.change

Description
-----------
This update is done to include the recent [Security Patch Commit](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/commit/ba4e25c350020abcb787a3a319fdf991bef70538) added to FreeRTOS-Plus-TCP main branch.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

freertos-plus-tcp: Update git submodule commit to include security patch

---

docs/release_checklist.md
release_changes/202406121230.change

Description
-----------
Add release checklist
Test Steps
-----------
Checklist:
----------
- [NA] I have tested my changes. No regression in existing tests.
- [NA] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------

Add release checklist

---

.gitlab-ci.yml
applications/helpers/CMakeLists.txt
applications/keyword_detection/CMakeLists.txt
components/aws_iot/CMakeLists.txt
docs/project_organisation.md
release_changes/202406241724.change
tools/scripts/build.sh

Description
-----------
Internal CI nightly tests should support testing FRI applications/integration tests using `FreeRTOS-Plus-TCP` and `IoT_vSocket` connectivity stacks, to do so, the following changes were made: 
* Integration tests nightly job is modified to use both stacks
* A new job is added to test FRI applications with `IoT_vSocket` stack as FreeRTOS-Plus-TCP stack is already covered by all other jobs.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

internal-ci: Add support for testing IoT_vSocket connectivity stack in nightly tests

---

manifest.yml
release_changes/202407110931.change
tools/scripts/check_listed_dependencies.py

Description
-----------
Update manifest to include tpip category. In addition, Currently `check_listed_dependencies.py`, only checks whether `license` attribute is mentioned in the `manifest.yml` for all the dependencies. Improve the script to check other mandatory attributes like `tpip-category`, `version` and `path`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Update manifest to include tpip category

---

manifest.yml
release_changes/202407250924.change

Description
-----------
The latest version contains a fix for memory leak in `C_FindObjects` API and using key IDs instead of deprecated key handles (Mbed TLS 3.6.0).
Test Steps
-----------
Validated the changes in the CI, no regressions observed.
Checklist:
----------
Related Issue
-----------

freerots-pkcs11-psa: Update to latest version

---

.github/.cSpellWords.txt
README.md
docs/components/aws_iot/aws_tool.md
release_changes/202407231054.change
tools/scripts/createIoTThings.py

The script contains tools used to create, destroy, and manage AWS IoT Things, Policies, Buckets, Roles, and Jobs. It is intended to automate the process of creating an OTA update.
Documentation for the script was also added at
`docs/components/aws_iot/aws_tool.md``.
This commit links to this documentation in the top-level `README.md`, under a new section called 'Tools'.
This commit stores generated credentials for new objects in the `credentials` directory by default, with unique file names per Thing.
The user can optionally specify the credentials directory.
It is possible to do any operation except for an OTA image update if `update-signature.txt` is not in the correct directory. A warning is generated if `update-signature.txt` is not present.
This script updates …

tools: Port, debug, and document createIoTThings.py

---

.devcontainer/Dockerfile
release_changes/202409051212.change.md
setup.cfg
tools/ci/pipeline-baseline-fri.yml
tools/scripts/container_post_startup.sh
tools/scripts/run.sh

Description
-----------
* devcontainer: Add missing tools and packages
* devcontainer: Use aws ecr registry instead of docker registry
* tools: Fix VSI audio option for Corstone-315
* devcontainer: Add ccache support
* ci: Use fixed pipeline nvm version
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Use aws ecr docker image

---

.github/.cSpellWords.txt
docs/components/aws_iot/aws_tool.md
release_changes/202408300915.change
tools/scripts/createIoTThings.py
tools/scripts/createIoTThings_settings.json

Description
-----------
Introduces a new command to `tools/scripts/createIoTThings.py` that
1. Creates a Thing and Policy.
2. Re-builds the target application (if required).
3. Creates a Bucket, Role, and Update.
This command is documented in `aws_tool.md`.
The command takes at most 2 command line arguments, with the rest
specified in a .json file, an example of which is also included in This
commit as well as the `aws_tool.md` documentation.
Only 3 fields in the settings `.json` need to be filled in.
The command also re-uses AWS entities where possible. E.g. if
the role specified by the `.json` already exists, it checks it can access the Bucket
name specified before re-using the role.
The motivation for this commit is to make creating OTA updates
easier.
This MR also introduces a new …

 Implement single command for all steps of creating OTA update

---

.github/.cSpellWords.txt
applications/keyword_detection/ml_interface.cc
applications/object_detection/ml_interface.cc
applications/speech_recognition/dsp/src/dsp_interfaces.cpp
applications/speech_recognition/dsp/src/dsp_task.cc
applications/speech_recognition/dsp/src/scheduler.cpp
applications/speech_recognition/ml_interface.cc
components/aws_iot/coremqtt_agent/integration/tests/test_freertos_agent_message.cpp
components/aws_iot/coremqtt_agent/integration/tests/test_mqtt_agent_task.cpp
release_changes/202409181115.change
tools/scripts/run_uncrustify.sh

Description
-----------
This PR does the following:
* `*.cc`, and `*.cpp` files were not internally checked by uncrustify code formatter tool, these files are now added to be checked and styled according to uncrustify suggestions.
* Unknown words are added to fix failures identified by the spell-checker tool in `iot_default_root_certificates.h` file available in `aws_configs`  directory for all applications except `blinky`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add internal CI improvements

---

docs/components/aws_iot/aws_tool.md
release_changes/202409131621.change
release_changes/202409162029.change
tools/scripts/createIoTThings.py
tools/scripts/createIoTThings_settings.json

Description
-----------
In createIoTThings.py there is a command that takes a .json config and deletes all AWS entities described in there. This PR extends that command to search the credentials directory, and identify AWS Thing certificates before asking to delete these Things and their possibly related entities (which are generated using the .json config as well). This PR also documents this command in aws_tool.md.
This PR extends support for the .json config introduced by create-update-simplified and cleanup-simplified. This PR also documents this change in aws_tool.md and updates the example .json config with 4 new fields. The user-inputted variables are now stored in a dictionary data type within the Python script, as this makes it possible to extract the logic for getting these …

Extend createiotthings py functionality

---

components/aws_iot/coremqtt_agent/integration/inc/mqtt_agent_task.h
components/aws_iot/coremqtt_agent/integration/src/mqtt_agent_task.c
components/aws_iot/coremqtt_agent/integration/tests/CMakeLists.txt
components/aws_iot/coremqtt_agent/integration/tests/config_mocks/inc/FreeRTOSConfig.h
components/aws_iot/coremqtt_agent/integration/tests/test_freertos_command_pool.cpp
components/aws_iot/coremqtt_agent/integration/tests/test_mqtt_agent_task.cpp
components/connectivity/iot_socket/CMakeLists.txt
components/freertos_kernel/library_mocks/inc/FreeRTOS.h
components/security/freertos_pkcs11_psa/CMakeLists.txt
docs/unit_testing.md
release_changes/202409111546.change

Description
-----------
This PR adds 7 new unit tests for the file freertos_command_pool.c.
Ideally, more tests would have been added.
However, due to how the code was written any tests that filled the command pool would require
(a) exposing structures the code is using internally, so would break if this was changed.
(b) large refactoring of the code, adding to it's public interface.
Additionally, this PR fixes some mocks and modifies `test_mqtt_agent_task.cpp` to match.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Add freertos_command_pool.c unit tests

---

applications/helpers/logging/mocks/inc/logging_stack.h
components/aws_iot/coremqtt/library_mocks/inc/core_mqtt.h
components/aws_iot/coremqtt/library_mocks/src/core_mqtt.c
components/aws_iot/coremqtt_agent/integration/inc/subscription_manager.h
components/aws_iot/coremqtt_agent/integration/src/subscription_manager.c
components/aws_iot/coremqtt_agent/integration/tests/CMakeLists.txt
components/aws_iot/coremqtt_agent/integration/tests/test_subscription_manager.cpp
release_changes/202408051552.change

Description
-----------
This PR modifies mocks to support subscription_manager.c, and implements 32 unit tests for the file.
This PR also adds one change to subscription_manager.c's debug logging.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

coremqtt-agent: Add unit tests for subscription_manager.c

---

manifest.yml
release_changes/202409241441.change.md
tools/scripts/check_listed_dependencies.py

Description
-----------
In addition to adding the `security-risk` attribute, update TPIP script to check if all the dependencies contains this attribute.
Test Steps
-----------
Checklist:
----------
- [NA] I have tested my changes. No regression in existing tests.
- [NA] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------

manifest: Add the `security-risk` attribute

---

applications/freertos_iot_libraries_tests/main.c
applications/helpers/provisioning/dev_mode_key_provisioning.c
applications/helpers/provisioning/dev_mode_key_provisioning.h
applications/keyword_detection/main.c
applications/object_detection/main.c
applications/speech_recognition/main.c
release_changes/202409101951.change.md

After successful provisioning, the code writes a pattern into the ITS, which could be checked on the next boot.
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

provisioning: Prevent re-provisioning

---

manifest.yml
release_changes/202410071620.change.md
tools/ci/aws_cleanup.py

Description
-----------
* Update Mbed TLS to v3.6.1 release
* Fix a CI issue
* With latest version of `boto`, `s3.list_buckets` API expects `ContinuationToken` instead of `nextToken`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Update Mbed TLS to v3.6.1 release and Fix CI issue

---

.gitlab-ci.yml
release_changes/202411201651.change.md

Description
-----------
* ci: Enable gitlab-ci cache
* ci: Adjust CI runner resources
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Enable cache in gitlab ci

---

applications/freertos_iot_libraries_tests/configs/freertos_config/FreeRTOSIPConfig.h
applications/helpers/ota_orchestrator/CMakeLists.txt
applications/helpers/ota_orchestrator/src/mqtt_helpers.c
applications/helpers/ota_orchestrator/src/ota_orchestrator.c
applications/helpers/ota_orchestrator/src/ota_os_freertos.c
applications/helpers/sntp/CMakeLists.txt
applications/keyword_detection/CMakeLists.txt
applications/keyword_detection/configs/aws_configs/CMakeLists.txt
applications/keyword_detection/configs/aws_configs/core_mqtt_config.h
applications/keyword_detection/configs/aws_configs/ota_config.h
applications/keyword_detection/main.c
applications/object_detection/CMakeLists.txt
applications/object_detection/configs/aws_configs/CMakeLists.txt
applications/object_detection/configs/aws_configs/core_mqtt_config.h
applications/object_detection/isp/CMakeLists.txt
applications/object_detection/main.c
applications/speech_recognition/CMakeLists.txt
applications/speech_recognition/configs/aws_configs/CMakeLists.txt
applications/speech_recognition/configs/aws_configs/core_mqtt_config.h
applications/speech_recognition/main.c
components/connectivity/freertos_plus_tcp/integration/CMakeLists.txt
components/connectivity/iot_vsocket/integration/CMakeLists.txt
components/tools/freertos_libraries_integration_tests/integration/CMakeLists.txt
manifest.yml
release_changes/202412161811.change.md

Description
-----------
Update to FreeRTOS LTS libraries `202406-LTS`
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Update to FreeRTOS LTS libraries `202406-LTS`

---

docs/development_environment/introduction.md
docs/development_environment/vscode_dev_env_build_and_debug.md
release_changes/202501231700.change.md
tools/ci/pyproject.toml
tools/ci/setup.cfg
tools/scripts/run_uncrustify.sh

Description
-----------
Add the needed changes resulting from updating the docker image used in the internal CI from v20.04 to v22.04.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Adapt to Ubuntu version update

---

.github/workflows/build.yaml
applications/helpers/ota_orchestrator/src/ota_orchestrator.c
applications/helpers/ota_orchestrator/src/ota_os_freertos.c
components/aws_iot/coremqtt_agent/integration/src/mqtt_agent_task.c
release_changes/202501301446.change.md

Description
-----------
Changes done as part of this PR:
- Do not suspend OTA agent after successful update.
- `vOtaNotActiveHook()` should be called whenever there are no OTA jobs available.
- Use `LogDebug` and `LogError` instead of `LogInfo` to follow the previous `ota-for-embedded-iot-sdk` library implementation (avoiding new issues).
- The `MQTT_AGENT_KEEP_ALIVE_INTERVAL_SECONDS` is increased to `100` as in case of using `SOFTWARE` inference with `speech-recognition` application the connection is dropped before the ML Inference is done as the software inference is generally much slower compared to the Ethos NPU. This connection drop cause the ML inference to have wrong results as the task is interrupted. Hence, increasing the keep alive interval to avoid the connection drop.
Test …

Add OTA Orchestrator fixes

---

.gitmodules
components/ai/ml_embedded_evaluation_kit/integration/README.md
components/ai/ml_embedded_evaluation_kit/integration/cmake/model/GenerateASRModel.cmake
components/ai/ml_embedded_evaluation_kit/integration/cmake/model/GenerateKWSModel.cmake
components/ai/ml_embedded_evaluation_kit/integration/cmake/model/GenerateObjectDetectionModel.cmake
manifest.yml
release_changes/202503181254.change.md
tools/ci/pipeline-baseline-fri.yml
tools/scripts/run.sh

Description
-----------
`DISPLAY` is a well-known system-wide variable used in Linux for GUI applications. Overwriting it in the script could lead to unintended side effects, especially when launching graphical applications. Renaming it to `HDLCD_GUI` to avoid such conflicts.
The current version of `setuptools` (59.6.0) is too old to meet the requirements of the packages installed during the pre-commit stage. To avoid conflicts with system packages, a virtual environment is used to update `setuptools` and then run pre-commit stage in internal CI.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

Fix conflicts with DISPLAY system wide variable

---

bsp/cmake/SetLinkerOptions.cmake
release_changes/202504031422.change.md

Description
-----------
Using `--map` linker option only will output the map file contents on the terminal without creating a new map file. Hence, adding the `--list` option which outputs these information to a map file.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

armclang: Fix map file generation

---

.github/workflows/ci.yml
README.md
docs/components/security/trusted_firmware-m/trusted_firmware-m.md
docs/development_environment/linux_dev_env.md
release_changes/202506091030.change.md

Description
-----------
This PR includes the following changes:
- Introduce a `dco-check` job in `.github/workflows/ci.yml` that runs on pull request events. The job loops over every commit in `origin/main..HEAD` and fails immediately if any commit lacks a properly formatted
Signed-off-by: <Name> <email>
footer, ensuring full compliance with our Developer Certificate of Origin (DCO) policy.
- Trusted Firmware-M has moved its public documentation from `tf-m-user-guide.trustedfirmware.org/` to `trustedfirmware-m.readthedocs.io`. Hence, switching to the new domain.
- Some of the newly added dependencies are missing in the development environment requirements document. Hence, adding these new dependencies.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By submitting …

Add GitHub DCO-check workflow and fix TF-M URLs

---

.gitlab-ci.yml
bsp/common/syscalls_stub.c
release_changes/202507041323.change.md

Description
-----------
`default-jdk` is already installed as part of the internal CI Docker image. Hence, there is no need to reinstall it in `.gitlab-ci.yml`
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci: Remove redundant default-jdk installation

---

release_changes/202507141540.change.md
tools/ci/pipeline-baseline-fri.yml
tools/scripts/copyright_date_check.py

Description
-----------
When a file with an Arm copyright header is modified, CI will fail if the header does not include the current year, and it will print the paths of the offending files.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------

ci-license: Check for current year in the license job
